<?php

use Bitrix\Main\Error;
use Bitrix\Main\Localization\Loc;
use Bitrix\Main\Web\Json;

\Bitrix\Main\UI\Extension::load("local.vue-apps.order");

if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) {
    die();
}
/** @var array $arParams */
/** @var array $arResult */
/** @global CMain $APPLICATION */
/** @global CUser $USER */
/** @var CBitrixComponentTemplate $this */
/** @var string $templateName */
/** @var string $templateFile */
/** @var string $templateFolder */
/** @var string $componentPath */
/** @var OpenSourceOrderComponent $component */

?>

<div id="twpxOrderMake"></div>

<script>
	const twpxordermake = new BX.OrderMake('#twpxOrderMake', {
		OPTIONS: {
			result: {
				'IS_AUTHORIZED': true,
				'LAST_ORDER_DATA': {
					'PERSON_TYPE': true,
					'DELIVERY': true,
					'PAY_SYSTEM': true,
					'PICK_UP': false
				},
				'ZIP_PROPERTY_CHANGED': 'N',
				'ORDER_DESCRIPTION': false,
				'SHOW_AUTH': false,
				'SHOW_EMPTY_BASKET': false,
				'AUTH': {
					'new_user_registration': 'Y',
					'new_user_registration_email_confirmation': 'N',
					'new_user_email_required': 'Y',
					'new_user_phone_auth': 'N',
					'new_user_phone_required': 'N'
				},
				'SMS_AUTH': [],
				'OK_MESSAGE': [],
				'GRID': {
					'DEFAULT_COLUMNS': false,
					'HEADERS': [{
						'id': 'NAME',
						'name': 'Название'
					}, {
						'id': 'PREVIEW_PICTURE',
						'name': 'Изображение'
					}, {
						'id': 'PROPS',
						'name': 'Свойства'
					}, {
						'id': 'QUANTITY',
						'name': 'Количество'
					}, {
						'id': 'SUM',
						'name': 'Сумма'
					}],
					'HEADERS_HIDDEN': [],
					'ROWS': {
						'13': {
							'id': '13',
							'data': {
								'ID': '13',
								'LID': 's1',
								'MODULE': 'catalog',
								'PRODUCT_ID': '204',
								'QUANTITY': '1',
								'WEIGHT': '0.00',
								'DELAY': 'N',
								'CAN_BUY': 'Y',
								'PRICE': '2699',
								'CUSTOM_PRICE': 'N',
								'BASE_PRICE': '2699',
								'PRODUCT_PRICE_ID': '163',
								'PRICE_TYPE_ID': '1',
								'CURRENCY': 'RUB',
								'BARCODE_MULTI': 'N',
								'RESERVED': 'N',
								'RESERVE_QUANTITY': '',
								'NAME': 'Спортивный Костюм Вечерний Спорт',
								'CATALOG_XML_ID': 'clothes_offers_s1',
								'VAT_RATE': '',
								'NOTES': 'Розничная цена',
								'DISCOUNT_PRICE': '0',
								'PRODUCT_PROVIDER_CLASS': '\\Bitrix\\Catalog\\Product\\CatalogProvider',
								'CALLBACK_FUNC': '',
								'ORDER_CALLBACK_FUNC': '',
								'PAY_CALLBACK_FUNC': '',
								'CANCEL_CALLBACK_FUNC': '',
								'DIMENSIONS': 'a:3:{s:5:\"WIDTH\";N;s:6:\"HEIGHT\";N;s:6:\"LENGTH\";N;}',
								'TYPE': '',
								'SET_PARENT_ID': '',
								'DETAIL_PAGE_URL': '/catalog/sportswear/sports-suit-evening-activities/',
								'FUSER_ID': '1',
								'MEASURE_CODE': '796',
								'MEASURE_NAME': 'шт',
								'ORDER_ID': '',
								'DATE_INSERT': '17.10.2024 15:58:40',
								'DATE_UPDATE': '29.10.2024 11:12:21',
								'PRODUCT_XML_ID': '456#461',
								'SUBSCRIBE': 'N',
								'RECOMMENDATION': '',
								'VAT_INCLUDED': 'N',
								'SORT': '100',
								'DATE_REFRESH': '',
								'DISCOUNT_NAME': '',
								'DISCOUNT_VALUE': '',
								'DISCOUNT_COUPON': '',
								'XML_ID': 'bx_67110a00a15ec',
								'MARKING_CODE_GROUP': '',
								'PRICE_FORMATED': '2&nbsp;699 &#8381;',
								'WEIGHT_FORMATED': '0 кг',
								'DISCOUNT_PRICE_PERCENT': '0',
								'DISCOUNT_PRICE_PERCENT_FORMATED': '0%',
								'BASE_PRICE_FORMATED': '2&nbsp;699 &#8381;',
								'PROPS': [{
									'CODE': 'ARTNUMBER',
									'VALUE': '189-06-03',
									'NAME': 'Артикул',
									'SORT': '1',
									'ID': '6'
								}, {
									'CODE': 'COLOR_REF',
									'VALUE': 'Белый',
									'NAME': 'Цвет',
									'SORT': '2',
									'ID': '7'
								}, {
									'CODE': 'SIZES_CLOTHES',
									'VALUE': 'XS',
									'NAME': 'Размеры одежды ',
									'SORT': '3',
									'ID': '8'
								}],
								'SUM_NUM': '2699',
								'SUM': '2&nbsp;699 &#8381;',
								'SUM_BASE': '2699',
								'SUM_BASE_FORMATED': '2&nbsp;699 &#8381;',
								'SUM_DISCOUNT_DIFF': '0',
								'SUM_DISCOUNT_DIFF_FORMATED': '0 &#8381;',
								'DETAIL_PICTURE': '174',
								'PREVIEW_TEXT': 'Прекрасный комплект, состоящий из футболки с округлым вырезом горловины и короткими рукавами и шорт. Модель выполнена из качественного материала. Отличный вариант на каждый день.',
								'PREVIEW_TEXT_TYPE': 'text',
								'PREVIEW_PICTURE_SRC': '',
								'DETAIL_PICTURE_SRC': '/upload/resize_cache/iblock/72b/160_160_1/g8zsmutdggqg5h70lvgnh9ftjgzi0vrw.jpg',
								'DETAIL_PICTURE_SRC_2X': '/upload/resize_cache/iblock/72b/320_320_1/g8zsmutdggqg5h70lvgnh9ftjgzi0vrw.jpg',
								'DETAIL_PICTURE_SRC_ORIGINAL': '/upload/iblock/72b/g8zsmutdggqg5h70lvgnh9ftjgzi0vrw.jpg',
								'MEASURE_TEXT': 'шт',
								'MEASURE': '796'
							},
							'actions': [],
							'columns': {
								'PROPS': 'Артикул:&nbsp;189-06-03<br />Цвет:&nbsp;Белый<br />Размеры&nbsp;одежды&nbsp;:&nbsp;XS<br />',
								'QUANTITY': '1&nbsp;шт'
							},
							'editable': true
						},
						'17': {
							'id': '17',
							'data': {
								'ID': '17',
								'LID': 's1',
								'MODULE': 'catalog',
								'PRODUCT_ID': '109',
								'QUANTITY': '1',
								'WEIGHT': '0.00',
								'DELAY': 'N',
								'CAN_BUY': 'Y',
								'PRICE': '3399.15',
								'CUSTOM_PRICE': 'N',
								'BASE_PRICE': '3999',
								'PRODUCT_PRICE_ID': '68',
								'PRICE_TYPE_ID': '1',
								'CURRENCY': 'RUB',
								'BARCODE_MULTI': 'N',
								'RESERVED': 'N',
								'RESERVE_QUANTITY': '',
								'NAME': 'Платье Красная Фея',
								'CATALOG_XML_ID': 'clothes_offers_s1',
								'VAT_RATE': '',
								'NOTES': 'Розничная цена',
								'DISCOUNT_PRICE': '599.85',
								'PRODUCT_PROVIDER_CLASS': '\\Bitrix\\Catalog\\Product\\CatalogProvider',
								'CALLBACK_FUNC': '',
								'ORDER_CALLBACK_FUNC': '',
								'PAY_CALLBACK_FUNC': '',
								'CANCEL_CALLBACK_FUNC': '',
								'DIMENSIONS': 'a:3:{s:5:\"WIDTH\";N;s:6:\"HEIGHT\";N;s:6:\"LENGTH\";N;}',
								'TYPE': '',
								'SET_PARENT_ID': '',
								'DETAIL_PAGE_URL': '/catalog/dresses/dress-red-fairy/',
								'FUSER_ID': '1',
								'MEASURE_CODE': '796',
								'MEASURE_NAME': 'шт',
								'ORDER_ID': '',
								'DATE_INSERT': '21.10.2024 15:22:05',
								'DATE_UPDATE': '29.10.2024 11:12:21',
								'PRODUCT_XML_ID': '280#285',
								'SUBSCRIBE': 'N',
								'RECOMMENDATION': '',
								'VAT_INCLUDED': 'N',
								'SORT': '200',
								'DATE_REFRESH': '',
								'DISCOUNT_NAME': '',
								'DISCOUNT_VALUE': '',
								'DISCOUNT_COUPON': '',
								'XML_ID': 'bx_6716476dab788',
								'MARKING_CODE_GROUP': '',
								'PRICE_FORMATED': '3&nbsp;399.15 &#8381;',
								'WEIGHT_FORMATED': '0 кг',
								'DISCOUNT_PRICE_PERCENT': '15',
								'DISCOUNT_PRICE_PERCENT_FORMATED': '15%',
								'BASE_PRICE_FORMATED': '3&nbsp;999 &#8381;',
								'PROPS': [{
									'CODE': 'ARTNUMBER',
									'VALUE': '144-15-05',
									'NAME': 'Артикул',
									'SORT': '1',
									'ID': '26'
								}, {
									'CODE': 'COLOR_REF',
									'VALUE': 'Красный',
									'NAME': 'Цвет',
									'SORT': '2',
									'ID': '27'
								}, {
									'CODE': 'SIZES_CLOTHES',
									'VALUE': 'XS',
									'NAME': 'Размеры одежды ',
									'SORT': '3',
									'ID': '28'
								}],
								'SUM_NUM': '3399.15',
								'SUM': '3&nbsp;399.15 &#8381;',
								'SUM_BASE': '3999',
								'SUM_BASE_FORMATED': '3&nbsp;999 &#8381;',
								'SUM_DISCOUNT_DIFF': '599.85',
								'SUM_DISCOUNT_DIFF_FORMATED': '599.85 &#8381;',
								'DETAIL_PICTURE': '72',
								'PREVIEW_PICTURE_SRC': '',
								'DETAIL_PICTURE_SRC': '/upload/resize_cache/iblock/69c/160_160_1/1boy3qpz8wpp0pdir7gosb6f1c5isedq.jpg',
								'DETAIL_PICTURE_SRC_2X': '/upload/resize_cache/iblock/69c/320_320_1/1boy3qpz8wpp0pdir7gosb6f1c5isedq.jpg',
								'DETAIL_PICTURE_SRC_ORIGINAL': '/upload/iblock/69c/1boy3qpz8wpp0pdir7gosb6f1c5isedq.jpg',
								'MEASURE_TEXT': 'шт',
								'MEASURE': '796'
							},
							'actions': [],
							'columns': {
								'PROPS': 'Артикул:&nbsp;144-15-05<br />Цвет:&nbsp;Красный<br />Размеры&nbsp;одежды&nbsp;:&nbsp;XS<br />',
								'QUANTITY': '1&nbsp;шт'
							},
							'editable': true
						}
					}
				},
				'PERSON_TYPE': {
					'1': {
						'ID': '1',
						'LID': 's1',
						'NAME': 'Физическое лицо',
						'CODE': '',
						'SORT': '100',
						'ACTIVE': 'Y',
						'XML_ID': '',
						'ENTITY_REGISTRY_TYPE': 'ORDER',
						'CHECKED': 'Y'
					},
					'2': {
						'ID': '2',
						'LID': 's1',
						'NAME': 'Юридическое лицо',
						'CODE': '',
						'SORT': '150',
						'ACTIVE': 'Y',
						'XML_ID': '',
						'ENTITY_REGISTRY_TYPE': 'ORDER'
					}
				},
				'PAY_SYSTEM': [{
					'ID': '4',
					'PAY_SYSTEM_ID': '4',
					'NAME': 'Банковские карты',
					'PSA_NAME': 'Банковские карты',
					'CODE': '',
					'SORT': '60',
					'DESCRIPTION': 'Оплата производится банковской картой через сервис ЮKassa. Подтверждением вашей оплаты является электронное почтовое уведомление, пришедшее после оплаты.',
					'PS_MODE': 'AC',
					'PS_CLIENT_TYPE': 'b2c',
					'HAVE_PRICE': 'N',
					'ACTIVE': 'Y',
					'ALLOW_EDIT_PAYMENT': 'Y',
					'IS_CASH': 'N',
					'AUTO_CHANGE_1C': 'N',
					'CAN_PRINT_CHECK': 'N',
					'ENTITY_REGISTRY_TYPE': 'ORDER',
					'XML_ID': '',
					'PSA_ID': '4',
					'PSA_ACTION_FILE': 'yandex',
					'PSA_RESULT_FILE': '',
					'PSA_NEW_WINDOW': 'N',
					'PSA_PERSON_TYPE_ID': '',
					'PSA_PARAMS': 'a:1:{s:16:\"BX_PAY_SYSTEM_ID\";i:4;}',
					'PSA_TARIF': '',
					'PSA_HAVE_PAYMENT': 'Y',
					'PSA_HAVE_ACTION': 'N',
					'PSA_HAVE_RESULT': 'N',
					'PSA_HAVE_PREPAY': 'N',
					'PSA_HAVE_RESULT_RECEIVE': 'Y',
					'PSA_ENCODING': '',
					'PSA_LOGOTIP': {
						'ID': '937',
						'TIMESTAMP_X': '17.10.2024 14:54:00',
						'MODULE_ID': '',
						'HEIGHT': '249',
						'WIDTH': '512',
						'FILE_SIZE': '74090',
						'CONTENT_TYPE': 'image/png',
						'SUBDIR': 'sale/paysystem/logotip/422',
						'FILE_NAME': 'wf5tkgngbiufxvcqryerwk8o3y0314gj.png',
						'ORIGINAL_NAME': 'yandex_cards.png',
						'DESCRIPTION': '',
						'HANDLER_ID': '',
						'EXTERNAL_ID': 'dde19a7f6b4d1a714b4cb0fb15bf0dd6',
						'VERSION_ORIGINAL_ID': '',
						'META': '',
						'SRC': '/upload/sale/paysystem/logotip/422/wf5tkgngbiufxvcqryerwk8o3y0314gj.png'
					},
					'CHECKED': 'Y',
					'PRICE': '0',
					'PSA_LOGOTIP_SRC': '/upload/resize_cache/sale/paysystem/logotip/422/300_300_1/wf5tkgngbiufxvcqryerwk8o3y0314gj.png',
					'PSA_LOGOTIP_SRC_2X': '/upload/sale/paysystem/logotip/422/wf5tkgngbiufxvcqryerwk8o3y0314gj.png',
					'PSA_LOGOTIP_SRC_ORIGINAL': '/upload/sale/paysystem/logotip/422/wf5tkgngbiufxvcqryerwk8o3y0314gj.png'
				}, {
					'ID': '2',
					'PAY_SYSTEM_ID': '2',
					'NAME': 'Наличные курьеру',
					'PSA_NAME': 'Наличные курьеру',
					'CODE': '',
					'SORT': '80',
					'DESCRIPTION': 'Оплата производится наличными деньгами, в момент получения заказа. Подтверждением вашей оплаты является фискальный кассовый чек, вручаемый во время получения и оплаты заказа.',
					'PS_MODE': '',
					'PS_CLIENT_TYPE': 'b2c',
					'HAVE_PRICE': 'N',
					'ACTIVE': 'Y',
					'ALLOW_EDIT_PAYMENT': 'Y',
					'IS_CASH': 'Y',
					'AUTO_CHANGE_1C': 'N',
					'CAN_PRINT_CHECK': 'N',
					'ENTITY_REGISTRY_TYPE': 'ORDER',
					'XML_ID': '',
					'PSA_ID': '2',
					'PSA_ACTION_FILE': 'cash',
					'PSA_RESULT_FILE': '',
					'PSA_NEW_WINDOW': 'N',
					'PSA_PERSON_TYPE_ID': '',
					'PSA_PARAMS': 'a:1:{s:16:\"BX_PAY_SYSTEM_ID\";i:2;}',
					'PSA_TARIF': '',
					'PSA_HAVE_PAYMENT': 'Y',
					'PSA_HAVE_ACTION': 'N',
					'PSA_HAVE_RESULT': 'N',
					'PSA_HAVE_PREPAY': 'N',
					'PSA_HAVE_RESULT_RECEIVE': 'N',
					'PSA_ENCODING': '',
					'PSA_LOGOTIP': {
						'ID': '935',
						'TIMESTAMP_X': '17.10.2024 14:54:00',
						'MODULE_ID': 'sale',
						'HEIGHT': '269',
						'WIDTH': '400',
						'FILE_SIZE': '3601',
						'CONTENT_TYPE': 'image/png',
						'SUBDIR': 'sale/paysystem/logotip/b80',
						'FILE_NAME': '0d3sp2z2v6rzqgj45is9g3l5qye91tyg.png',
						'ORIGINAL_NAME': 'cash.png',
						'DESCRIPTION': '',
						'HANDLER_ID': '',
						'EXTERNAL_ID': '9b8ef2a801585a44ac330633f08c78b8',
						'VERSION_ORIGINAL_ID': '',
						'META': '',
						'SRC': '/upload/sale/paysystem/logotip/b80/0d3sp2z2v6rzqgj45is9g3l5qye91tyg.png'
					},
					'PRICE': '0',
					'PSA_LOGOTIP_SRC': '/upload/resize_cache/sale/paysystem/logotip/b80/300_300_1/0d3sp2z2v6rzqgj45is9g3l5qye91tyg.png',
					'PSA_LOGOTIP_SRC_2X': '/upload/sale/paysystem/logotip/b80/0d3sp2z2v6rzqgj45is9g3l5qye91tyg.png',
					'PSA_LOGOTIP_SRC_ORIGINAL': '/upload/sale/paysystem/logotip/b80/0d3sp2z2v6rzqgj45is9g3l5qye91tyg.png'
				}],
				'INNER_PAY_SYSTEM': '',
				'DELIVERY': {
					'2': {
						'ID': '2',
						'NAME': 'Доставка курьером',
						'OWN_NAME': 'Доставка курьером',
						'DESCRIPTION': 'Доставка осуществляется в течение дня в удобное для вас время.',
						'FIELD_NAME': 'DELIVERY_ID',
						'CURRENCY': 'RUB',
						'SORT': '100',
						'EXTRA_SERVICES': [],
						'STORE': [],
						'LOGOTIP': {
							'ID': '941',
							'TIMESTAMP_X': '17.10.2024 14:54:02',
							'MODULE_ID': 'sale',
							'HEIGHT': '249',
							'WIDTH': '512',
							'FILE_SIZE': '11154',
							'CONTENT_TYPE': 'image/png',
							'SUBDIR': 'sale/delivery/logotip/3ed',
							'FILE_NAME': '3w4kkd8yebaffkmxudq5ezgqb323czc3.png',
							'ORIGINAL_NAME': 'courier_logo.png',
							'DESCRIPTION': '',
							'HANDLER_ID': '',
							'EXTERNAL_ID': '17f1f2062bccc55641fb9ae5059e88a8',
							'VERSION_ORIGINAL_ID': '',
							'META': '',
							'SRC': '/upload/sale/delivery/logotip/3ed/3w4kkd8yebaffkmxudq5ezgqb323czc3.png'
						},
						'LOGOTIP_SRC': '/upload/resize_cache/sale/delivery/logotip/3ed/300_300_1/3w4kkd8yebaffkmxudq5ezgqb323czc3.png',
						'LOGOTIP_SRC_2X': '/upload/sale/delivery/logotip/3ed/3w4kkd8yebaffkmxudq5ezgqb323czc3.png',
						'LOGOTIP_SRC_ORIGINAL': '/upload/sale/delivery/logotip/3ed/3w4kkd8yebaffkmxudq5ezgqb323czc3.png'
					},
					'3': {
						'CHECKED': 'Y',
						'PRICE': '0',
						'PRICE_FORMATED': '0 &#8381;',
						'CALCULATE_DESCRIPTION': '',
						'ID': '3',
						'NAME': 'Самовывоз',
						'OWN_NAME': 'Самовывоз',
						'DESCRIPTION': 'Вы можете самостоятельно забрать заказ из нашего магазина.',
						'FIELD_NAME': 'DELIVERY_ID',
						'CURRENCY': 'RUB',
						'SORT': '200',
						'EXTRA_SERVICES': [],
						'STORE': [],
						'LOGOTIP': {
							'ID': '942',
							'TIMESTAMP_X': '17.10.2024 14:54:02',
							'MODULE_ID': 'sale',
							'HEIGHT': '249',
							'WIDTH': '512',
							'FILE_SIZE': '7852',
							'CONTENT_TYPE': 'image/png',
							'SUBDIR': 'sale/delivery/logotip/137',
							'FILE_NAME': 'u5kni7fq24sn3maq1dwqavrd165ojq7q.png',
							'ORIGINAL_NAME': 'self_logo.png',
							'DESCRIPTION': '',
							'HANDLER_ID': '',
							'EXTERNAL_ID': '3fb8226097058adf0df1e7509cfa0a29',
							'VERSION_ORIGINAL_ID': '',
							'META': '',
							'SRC': '/upload/sale/delivery/logotip/137/u5kni7fq24sn3maq1dwqavrd165ojq7q.png'
						},
						'LOGOTIP_SRC': '/upload/resize_cache/sale/delivery/logotip/137/300_300_1/u5kni7fq24sn3maq1dwqavrd165ojq7q.png',
						'LOGOTIP_SRC_2X': '/upload/sale/delivery/logotip/137/u5kni7fq24sn3maq1dwqavrd165ojq7q.png',
						'LOGOTIP_SRC_ORIGINAL': '/upload/sale/delivery/logotip/137/u5kni7fq24sn3maq1dwqavrd165ojq7q.png'
					}
				},
				'USER_PROFILES': [],
				'ORDER_PROP': {
					'groups': [{
						'ID': '1',
						'PERSON_TYPE_ID': '1',
						'NAME': 'Личные данные',
						'CODE': '',
						'SORT': '100'
					}, {
						'ID': '2',
						'PERSON_TYPE_ID': '1',
						'NAME': 'Данные для доставки',
						'CODE': '',
						'SORT': '200'
					}],
					'properties': [{
						'ID': '1',
						'PERSON_TYPE_ID': '1',
						'NAME': 'Ф.И.О.',
						'TYPE': 'STRING',
						'REQUIRED': 'Y',
						'DEFAULT_VALUE': '',
						'SORT': '100',
						'USER_PROPS': 'Y',
						'IS_LOCATION': 'N',
						'PROPS_GROUP_ID': '1',
						'DESCRIPTION': '',
						'IS_EMAIL': 'N',
						'IS_PROFILE_NAME': 'Y',
						'IS_PAYER': 'Y',
						'IS_LOCATION4TAX': 'N',
						'IS_FILTERED': 'Y',
						'CODE': 'FIO',
						'IS_ZIP': 'N',
						'IS_PHONE': 'N',
						'IS_ADDRESS': 'N',
						'IS_ADDRESS_FROM': 'N',
						'IS_ADDRESS_TO': 'N',
						'ACTIVE': 'Y',
						'UTIL': 'N',
						'INPUT_FIELD_LOCATION': '0',
						'MULTIPLE': 'N',
						'ENTITY_TYPE': 'ORDER',
						'SIZE': '40',
						'RELATION': [],
						'VALUE': ['<Без имени>']
					}, {
						'ID': '2',
						'PERSON_TYPE_ID': '1',
						'NAME': 'E-Mail',
						'TYPE': 'STRING',
						'REQUIRED': 'Y',
						'DEFAULT_VALUE': '',
						'SORT': '110',
						'USER_PROPS': 'Y',
						'IS_LOCATION': 'N',
						'PROPS_GROUP_ID': '1',
						'DESCRIPTION': '',
						'IS_EMAIL': 'Y',
						'IS_PROFILE_NAME': 'N',
						'IS_PAYER': 'N',
						'IS_LOCATION4TAX': 'N',
						'IS_FILTERED': 'Y',
						'CODE': 'EMAIL',
						'IS_ZIP': 'N',
						'IS_PHONE': 'N',
						'IS_ADDRESS': 'N',
						'IS_ADDRESS_FROM': 'N',
						'IS_ADDRESS_TO': 'N',
						'ACTIVE': 'Y',
						'UTIL': 'N',
						'INPUT_FIELD_LOCATION': '0',
						'MULTIPLE': 'N',
						'ENTITY_TYPE': 'ORDER',
						'SIZE': '40',
						'RELATION': [],
						'VALUE': ['support@twinpx.ru']
					}, {
						'ID': '3',
						'PERSON_TYPE_ID': '1',
						'NAME': 'Телефон',
						'TYPE': 'STRING',
						'REQUIRED': 'Y',
						'DEFAULT_VALUE': '',
						'SORT': '120',
						'USER_PROPS': 'Y',
						'IS_LOCATION': 'N',
						'PROPS_GROUP_ID': '1',
						'DESCRIPTION': '',
						'IS_EMAIL': 'N',
						'IS_PROFILE_NAME': 'N',
						'IS_PAYER': 'N',
						'IS_LOCATION4TAX': 'N',
						'IS_FILTERED': 'N',
						'CODE': 'PHONE',
						'IS_ZIP': 'N',
						'IS_PHONE': 'Y',
						'IS_ADDRESS': 'N',
						'IS_ADDRESS_FROM': 'N',
						'IS_ADDRESS_TO': 'N',
						'ACTIVE': 'Y',
						'UTIL': 'N',
						'INPUT_FIELD_LOCATION': '0',
						'MULTIPLE': 'N',
						'ENTITY_TYPE': 'ORDER',
						'RELATION': [],
						'VALUE': ['']
					}, {
						'ID': '6',
						'PERSON_TYPE_ID': '1',
						'NAME': 'Местоположение',
						'TYPE': 'LOCATION',
						'REQUIRED': 'Y',
						'DEFAULT_VALUE': '0000073738',
						'SORT': '140',
						'USER_PROPS': 'Y',
						'IS_LOCATION': 'Y',
						'PROPS_GROUP_ID': '2',
						'DESCRIPTION': '',
						'IS_EMAIL': 'N',
						'IS_PROFILE_NAME': 'N',
						'IS_PAYER': 'N',
						'IS_LOCATION4TAX': 'N',
						'IS_FILTERED': 'N',
						'CODE': 'LOCATION',
						'IS_ZIP': 'N',
						'IS_PHONE': 'N',
						'IS_ADDRESS': 'N',
						'IS_ADDRESS_FROM': 'N',
						'IS_ADDRESS_TO': 'N',
						'ACTIVE': 'Y',
						'UTIL': 'N',
						'INPUT_FIELD_LOCATION': '5',
						'MULTIPLE': 'N',
						'ENTITY_TYPE': 'ORDER',
						'SIZE': '40',
						'RELATION': [],
						'VALUE': ['0000073738']
					}, {
						'ID': '7',
						'PERSON_TYPE_ID': '1',
						'NAME': 'Адрес доставки',
						'TYPE': 'STRING',
						'REQUIRED': 'Y',
						'DEFAULT_VALUE': '',
						'SORT': '150',
						'USER_PROPS': 'Y',
						'IS_LOCATION': 'N',
						'PROPS_GROUP_ID': '2',
						'DESCRIPTION': '',
						'IS_EMAIL': 'N',
						'IS_PROFILE_NAME': 'N',
						'IS_PAYER': 'N',
						'IS_LOCATION4TAX': 'N',
						'IS_FILTERED': 'N',
						'CODE': 'ADDRESS',
						'IS_ZIP': 'N',
						'IS_PHONE': 'N',
						'IS_ADDRESS': 'Y',
						'IS_ADDRESS_FROM': 'N',
						'IS_ADDRESS_TO': 'N',
						'ACTIVE': 'Y',
						'UTIL': 'N',
						'INPUT_FIELD_LOCATION': '0',
						'MULTIPLE': 'N',
						'ENTITY_TYPE': 'ORDER',
						'MULTILINE': 'Y',
						'COLS': '30',
						'ROWS': '3',
						'RELATION': [],
						'VALUE': ['']
					}]
				},
				'STORE_LIST': [],
				'BUYER_STORE': '0',
				'COUPON_LIST': [],
				'PAY_CURRENT_ACCOUNT': 'N',
				'PAY_FROM_ACCOUNT': 'N',
				'CURRENT_BUDGET_FORMATED': '',
				'TOTAL': {
					'BASKET_POSITIONS': '2',
					'PRICE_WITHOUT_DISCOUNT_VALUE': '6698',
					'PRICE_WITHOUT_DISCOUNT': '6&nbsp;698 &#8381;',
					'BASKET_PRICE_DISCOUNT_DIFF_VALUE': '599.85',
					'BASKET_PRICE_DISCOUNT_DIFF': '599.85 &#8381;',
					'PAYED_FROM_ACCOUNT_FORMATED': false,
					'ORDER_TOTAL_PRICE': '6098.15',
					'ORDER_TOTAL_PRICE_FORMATED': '6&nbsp;098.15 &#8381;',
					'ORDER_TOTAL_LEFT_TO_PAY': '',
					'ORDER_TOTAL_LEFT_TO_PAY_FORMATED': '',
					'ORDER_WEIGHT': '0',
					'ORDER_WEIGHT_FORMATED': '0 кг',
					'ORDER_PRICE': '6098.15',
					'ORDER_PRICE_FORMATED': '6&nbsp;098.15 &#8381;',
					'USE_VAT': false,
					'VAT_RATE': '0',
					'VAT_SUM': '0',
					'VAT_SUM_FORMATED': '0 &#8381;',
					'TAX_PRICE': '0',
					'TAX_LIST': [],
					'DISCOUNT_PRICE': '599.85',
					'DISCOUNT_PRICE_FORMATED': '599.85 &#8381;',
					'DELIVERY_PRICE': '0',
					'DELIVERY_PRICE_FORMATED': '0 &#8381;',
					'PAY_SYSTEM_PRICE': '',
					'PAY_SYSTEM_PRICE_FORMATTED': ''
				},
				'ERROR': [],
				'WARNING': []
			},
			locations: {
				'6': {
					'template': 'search',
					'output': ['	<div id=\"sls-38863\" class=\"bx-sls \">\n\n				<div class=\"dropdown-block bx-ui-sls-input-block\">\n\n			<span class=\"dropdown-icon\"><\/span>\n			<input type=\"text\" autocomplete=\"off\" name=\"ORDER_PROP_6\" value=\"0000073738\" class=\"dropdown-field\" placeholder=\"Введите название ...\" />\n\n			<div class=\"dropdown-fade2white\"><\/div>\n			<div class=\"bx-ui-sls-loader\"><\/div>\n			<div class=\"bx-ui-sls-clear\" title=\"Отменить выбор\"><\/div>\n			<div class=\"bx-ui-sls-pane\"><\/div>\n\n		<\/div>\n\n		<script type=\"text/html\" data-template-id=\"bx-ui-sls-error\">\n			<div class=\"bx-ui-sls-error\">\n				<div><\/div>\n				{{message}}\n			<\/div>\n		<\/script>\n\n		<script type=\"text/html\" data-template-id=\"bx-ui-sls-dropdown-item\">\n			<div class=\"dropdown-item bx-ui-sls-variant\">\n				<span class=\"dropdown-item-text\">{{display_wrapped}}<\/span>\n							<\/div>\n		<\/script>\n\n		<div class=\"bx-ui-sls-error-message\">\n					<\/div>\n\n	<\/div>\n\n	<script>\n\n		if (!window.BX && top.BX)\n			window.BX = top.BX;\n\n				if (typeof window.BX.locationsDeferred == \'undefined\') window.BX.locationsDeferred = {};\n		window.BX.locationsDeferred[\'6\'] = function () {\n					if (typeof window.BX.locationSelectors == \'undefined\') window.BX.locationSelectors = {};\n			window.BX.locationSelectors[\'6\'] =\n			\n			new BX.Sale.component.location.selector.search({\'scope\':\'sls-38863\',\'source\':\'/bitrix/components/bitrix/sale.location.selector.search/get.php\',\'query\':{\'FILTER\':{\'EXCLUDE_ID\':0,\'SITE_ID\':\'s1\'},\'BEHAVIOUR\':{\'SEARCH_BY_PRIMARY\':\'0\',\'LANGUAGE_ID\':\'ru\'}},\'selectedItem\':88,\'knownItems\':{\'88\':{\'CODE\':\'0000073738\',\'TYPE_ID\':\'5\',\'PATH\':[1],\'VALUE\':88,\'DISPLAY\':\'Москва\'},\'1\':{\'CODE\':\'0000028023\',\'TYPE_ID\':\'1\',\'PATH\':[],\'VALUE\':1,\'DISPLAY\':\'Россия\'}},\'provideLinkBy\':\'code\',\'messages\':{\'nothingFound\':\'К сожалению, ничего не найдено\',\'error\':\'К сожалению, произошла внутренняя ошибка\'},\'callback\':\'submitFormProxy\',\'useSpawn\':false,\'usePopup\':false,\'initializeByGlobalEvent\':\'\',\'globalEventScope\':\'\',\'pathNames\':{\'1\':\'Россия\',\'88\':\'Москва\'},\'types\':{\'1\':{\'CODE\':\'COUNTRY\'},\'2\':{\'CODE\':\'COUNTRY_DISTRICT\'},\'3\':{\'CODE\':\'REGION\'},\'4\':{\'CODE\':\'SUBREGION\'},\'5\':{\'CODE\':\'CITY\'},\'6\':{\'CODE\':\'VILLAGE\'},\'7\':{\'CODE\':\'STREET\'}}});\n\n				};\n		\n	<\/script>\n\n'],
					'showAlt': false,
					'lastValue': '0000073738',
					'coordinates': {
						'LONGITUDE': '0.000000',
						'LATITUDE': '0.000000'
					}
				}
			},
			params: {
				'PAY_FROM_ACCOUNT': 'Y',
				'COUNT_DELIVERY_TAX': 'N',
				'COUNT_DISCOUNT_4_ALL_QUANTITY': 'N',
				'ONLY_FULL_PAY_FROM_ACCOUNT': 'N',
				'ALLOW_AUTO_REGISTER': 'Y',
				'SEND_NEW_USER_NOTIFY': 'Y',
				'DELIVERY_NO_AJAX': 'N',
				'TEMPLATE_LOCATION': 'popup',
				'PROP_1': [],
				'PATH_TO_BASKET': '/personal/cart/',
				'PATH_TO_PERSONAL': '/personal/order/',
				'PATH_TO_PAYMENT': '/personal/order/payment/',
				'PATH_TO_ORDER': '/personal/order/make/',
				'SET_TITLE': 'Y',
				'SHOW_ACCOUNT_NUMBER': 'Y',
				'DELIVERY_NO_SESSION': 'Y',
				'COMPATIBLE_MODE': 'N',
				'BASKET_POSITION': 'before',
				'BASKET_IMAGES_SCALING': 'adaptive',
				'SERVICES_IMAGES_SCALING': 'adaptive',
				'USER_CONSENT': 'Y',
				'USER_CONSENT_ID': '2',
				'USER_CONSENT_IS_CHECKED': 'Y',
				'USER_CONSENT_IS_LOADED': 'Y',
				'CACHE_TYPE': 'A',
				'USE_PRELOAD': 'Y',
				'ACTION_VARIABLE': 'soa-action',
				'NO_PERSONAL': 'N',
				'PATH_TO_AUTH': '/auth/',
				'USE_PREPAYMENT': 'N',
				'DISPLAY_IMG_HEIGHT': '90',
				'SHOW_VAT_PRICE': 'Y',
				'DELIVERY_TO_PAYSYSTEM': 'd2p',
				'DISABLE_BASKET_REDIRECT': 'N',
				'EMPTY_BASKET_HINT_PATH': '/',
				'CURRENT_PAGE': '/personal/order/make/index4.php',
				'IS_LANDING_SHOP': 'N',
				'ALLOW_APPEND_ORDER': 'Y',
				'ALLOW_NEW_PROFILE': 'Y',
				'SHOW_NOT_CALCULATED_DELIVERIES': 'Y',
				'SPOT_LOCATION_BY_GEOIP': 'Y',
				'PRODUCT_COLUMNS': {
					'NAME': 'Название',
					'PREVIEW_PICTURE': 'Изображение',
					'PROPS': 'Свойства',
					'QUANTITY': 'Количество',
					'SUM': 'Сумма'
				},
				'PRODUCT_COLUMNS_VISIBLE': ['PREVIEW_PICTURE', 'PROPS'],
				'PRODUCT_COLUMNS_HIDDEN': [],
				'USE_PHONE_NORMALIZATION': 'Y',
				'~PAY_FROM_ACCOUNT': 'Y',
				'~COUNT_DELIVERY_TAX': 'N',
				'~COUNT_DISCOUNT_4_ALL_QUANTITY': 'N',
				'~ONLY_FULL_PAY_FROM_ACCOUNT': 'N',
				'~ALLOW_AUTO_REGISTER': 'Y',
				'~SEND_NEW_USER_NOTIFY': 'Y',
				'~DELIVERY_NO_AJAX': 'N',
				'~TEMPLATE_LOCATION': 'popup',
				'~PROP_1': [],
				'~PATH_TO_BASKET': '/personal/cart/',
				'~PATH_TO_PERSONAL': '/personal/order/',
				'~PATH_TO_PAYMENT': '/personal/order/payment/',
				'~PATH_TO_ORDER': '/personal/order/make/',
				'~SET_TITLE': 'Y',
				'~SHOW_ACCOUNT_NUMBER': 'Y',
				'~DELIVERY_NO_SESSION': 'Y',
				'~COMPATIBLE_MODE': 'N',
				'~BASKET_POSITION': 'before',
				'~BASKET_IMAGES_SCALING': 'adaptive',
				'~SERVICES_IMAGES_SCALING': 'adaptive',
				'~USER_CONSENT': 'Y',
				'~USER_CONSENT_ID': '2',
				'~USER_CONSENT_IS_CHECKED': 'Y',
				'~USER_CONSENT_IS_LOADED': 'Y',
				'~CACHE_TYPE': 'A',
				'~USE_PRELOAD': 'Y',
				'~ACTION_VARIABLE': 'soa-action',
				'~NO_PERSONAL': 'N',
				'~PATH_TO_AUTH': '/auth/',
				'~USE_PREPAYMENT': 'N',
				'~DISPLAY_IMG_HEIGHT': '90',
				'~SHOW_VAT_PRICE': 'Y',
				'~DELIVERY_TO_PAYSYSTEM': 'd2p',
				'~DISABLE_BASKET_REDIRECT': 'N',
				'~EMPTY_BASKET_HINT_PATH': '/',
				'~CURRENT_PAGE': '/personal/order/make/index4.php',
				'~IS_LANDING_SHOP': 'N',
				'~ALLOW_APPEND_ORDER': 'Y',
				'~ALLOW_NEW_PROFILE': 'Y',
				'~SHOW_NOT_CALCULATED_DELIVERIES': 'Y',
				'~SPOT_LOCATION_BY_GEOIP': 'Y',
				'~PRODUCT_COLUMNS': {
					'NAME': 'Название',
					'PREVIEW_PICTURE': 'Изображение',
					'PROPS': 'Свойства',
					'QUANTITY': 'Количество',
					'SUM': 'Сумма'
				},
				'~PRODUCT_COLUMNS_VISIBLE': ['PREVIEW_PICTURE', 'PROPS'],
				'~PRODUCT_COLUMNS_HIDDEN': [],
				'~USE_PHONE_NORMALIZATION': 'Y',
				'TEMPLATE_THEME': '',
				'SHOW_ORDER_BUTTON': 'final_step',
				'SHOW_TOTAL_ORDER_BUTTON': 'N',
				'SHOW_PAY_SYSTEM_LIST_NAMES': 'Y',
				'SHOW_PAY_SYSTEM_INFO_NAME': 'Y',
				'SHOW_DELIVERY_LIST_NAMES': 'Y',
				'SHOW_DELIVERY_INFO_NAME': 'Y',
				'SHOW_DELIVERY_PARENT_NAMES': 'Y',
				'SHOW_STORES_IMAGES': 'Y',
				'SKIP_USELESS_BLOCK': 'Y',
				'SHOW_BASKET_HEADERS': 'N',
				'DELIVERY_FADE_EXTRA_SERVICES': 'N',
				'SHOW_NEAREST_PICKUP': 'N',
				'DELIVERIES_PER_PAGE': '9',
				'PAY_SYSTEMS_PER_PAGE': '9',
				'PICKUPS_PER_PAGE': '5',
				'SHOW_PICKUP_MAP': 'Y',
				'SHOW_MAP_IN_PROPS': 'N',
				'PICKUP_MAP_TYPE': 'yandex',
				'HIDE_ORDER_DESCRIPTION': 'N',
				'ALLOW_USER_PROFILES': 'N',
				'SHOW_COUPONS': 'Y',
				'SHOW_COUPONS_BASKET': 'Y',
				'SHOW_COUPONS_DELIVERY': 'Y',
				'SHOW_COUPONS_PAY_SYSTEM': 'Y',
				'USE_YM_GOALS': 'N',
				'YM_GOALS_COUNTER': '',
				'YM_GOALS_INITIALIZE': 'BX-order-init',
				'YM_GOALS_EDIT_REGION': 'BX-region-edit',
				'YM_GOALS_EDIT_DELIVERY': 'BX-delivery-edit',
				'YM_GOALS_EDIT_PICKUP': 'BX-pickUp-edit',
				'YM_GOALS_EDIT_PAY_SYSTEM': 'BX-paySystem-edit',
				'YM_GOALS_EDIT_PROPERTIES': 'BX-properties-edit',
				'YM_GOALS_EDIT_BASKET': 'BX-basket-edit',
				'YM_GOALS_NEXT_REGION': 'BX-region-next',
				'YM_GOALS_NEXT_DELIVERY': 'BX-delivery-next',
				'YM_GOALS_NEXT_PICKUP': 'BX-pickUp-next',
				'YM_GOALS_NEXT_PAY_SYSTEM': 'BX-paySystem-next',
				'YM_GOALS_NEXT_PROPERTIES': 'BX-properties-next',
				'YM_GOALS_NEXT_BASKET': 'BX-basket-next',
				'YM_GOALS_SAVE_ORDER': 'BX-order-save',
				'USE_ENHANCED_ECOMMERCE': 'N',
				'DATA_LAYER_NAME': 'dataLayer',
				'BRAND_PROPERTY': '',
				'SHOW_MAP_FOR_DELIVERIES': [],
				'HIDE_DETAIL_PAGE_URL': 'N',
				'MESS_AUTH_BLOCK_NAME': 'Авторизация',
				'MESS_REG_BLOCK_NAME': 'Регистрация',
				'MESS_BASKET_BLOCK_NAME': 'Товары в заказе',
				'MESS_REGION_BLOCK_NAME': 'Регион доставки',
				'MESS_PAYMENT_BLOCK_NAME': 'Оплата',
				'MESS_DELIVERY_BLOCK_NAME': 'Доставка',
				'MESS_BUYER_BLOCK_NAME': 'Покупатель',
				'MESS_BACK': 'Назад',
				'MESS_FURTHER': 'Далее',
				'MESS_EDIT': 'изменить',
				'~MESS_ORDER': 'Оформить заказ',
				'MESS_ORDER': 'Оформить заказ',
				'MESS_PRICE': 'Стоимость',
				'MESS_PERIOD': 'Срок доставки',
				'MESS_NAV_BACK': 'Назад',
				'MESS_NAV_FORWARD': 'Вперед',
				'MESS_PRICE_FREE': 'бесплатно',
				'MESS_ECONOMY': 'Экономия',
				'MESS_REGISTRATION_REFERENCE': 'Если вы впервые на сайте, и хотите, чтобы мы вас помнили, и все ваши заказы сохранялись, заполните регистрационную форму.',
				'MESS_AUTH_REFERENCE_1': 'Символом \"звездочка\" (*) отмечены обязательные для заполнения поля.',
				'MESS_AUTH_REFERENCE_2': 'После регистрации вы получите информационное письмо.',
				'MESS_AUTH_REFERENCE_3': 'Личные сведения, полученные в распоряжение интернет-магазина при регистрации или каким-либо иным образом, не будут без разрешения пользователей передаваться третьим организациям и лицам за исключением ситуаций, когда этого требует закон или судебное решение.',
				'MESS_ADDITIONAL_PROPS': 'Дополнительные свойства',
				'MESS_USE_COUPON': 'Применить купон',
				'MESS_COUPON': 'Купон',
				'MESS_PERSON_TYPE': 'Тип плательщика',
				'MESS_SELECT_PROFILE': 'Выберите профиль',
				'MESS_REGION_REFERENCE': 'Выберите свой город в списке. Если вы не нашли свой город, выберите \"другое местоположение\", а город впишите в поле \"Город\"',
				'MESS_PICKUP_LIST': 'Пункты самовывоза:',
				'MESS_NEAREST_PICKUP_LIST': 'Ближайшие пункты:',
				'MESS_SELECT_PICKUP': 'Выбрать',
				'MESS_INNER_PS_BALANCE': 'На вашем пользовательском счете:',
				'MESS_ORDER_DESC': 'Комментарии к заказу:',
				'MESS_PRELOAD_ORDER_TITLE': '',
				'MESS_SUCCESS_PRELOAD_TEXT': 'Вы заказывали в нашем интернет-магазине, поэтому мы заполнили все данные автоматически.<br />\nЕсли все заполнено верно, нажмите кнопку \"#ORDER_BUTTON#\".\n',
				'MESS_FAIL_PRELOAD_TEXT': 'Вы заказывали в нашем интернет-магазине, поэтому мы заполнили все данные автоматически.<br />\nОбратите внимание на развернутый блок с информацией о заказе. Здесь вы можете внести необходимые изменения или \nоставить как есть и нажать кнопку \"#ORDER_BUTTON#\".\n',
				'MESS_DELIVERY_CALC_ERROR_TITLE': 'Не удалось рассчитать стоимость доставки.',
				'MESS_DELIVERY_CALC_ERROR_TEXT': 'Вы можете продолжить оформление заказа, а чуть позже менеджер магазина свяжется с вами и уточнит информацию по доставке.',
				'MESS_PAY_SYSTEM_PAYABLE_ERROR': 'Вы сможете оплатить заказ после того, как менеджер проверит наличие полного комплекта товаров на складе. Сразу после проверки вы получите письмо с инструкциями по оплате. Оплатить заказ можно будет в персональном разделе сайта.'
			},
			signedParamsString: 'YToxNzU6e3M6MTY6IlBBWV9GUk9NX0FDQ09VTlQiO3M6MToiWSI7czoxODoiQ09VTlRfREVMSVZFUllfVEFYIjtzOjE6Ik4iO3M6Mjk6IkNPVU5UX0RJU0NPVU5UXzRfQUxMX1FVQU5USVRZIjtzOjE6Ik4iO3M6MjY6Ik9OTFlfRlVMTF9QQVlfRlJPTV9BQ0NPVU5UIjtzOjE6Ik4iO3M6MTk6IkFMTE9XX0FVVE9fUkVHSVNURVIiO3M6MToiWSI7czoyMDoiU0VORF9ORVdfVVNFUl9OT1RJRlkiO3M6MToiWSI7czoxNjoiREVMSVZFUllfTk9fQUpBWCI7czoxOiJOIjtzOjE3OiJURU1QTEFURV9MT0NBVElPTiI7czo1OiJwb3B1cCI7czo2OiJQUk9QXzEiO2E6MDp7fXM6MTQ6IlBBVEhfVE9fQkFTS0VUIjtzOjE1OiIvcGVyc29uYWwvY2FydC8iO3M6MTY6IlBBVEhfVE9fUEVSU09OQUwiO3M6MTY6Ii9wZXJzb25hbC9vcmRlci8iO3M6MTU6IlBBVEhfVE9fUEFZTUVOVCI7czoyNDoiL3BlcnNvbmFsL29yZGVyL3BheW1lbnQvIjtzOjEzOiJQQVRIX1RPX09SREVSIjtzOjIxOiIvcGVyc29uYWwvb3JkZXIvbWFrZS8iO3M6OToiU0VUX1RJVExFIjtzOjE6IlkiO3M6MTk6IlNIT1dfQUNDT1VOVF9OVU1CRVIiO3M6MToiWSI7czoxOToiREVMSVZFUllfTk9fU0VTU0lPTiI7czoxOiJZIjtzOjE1OiJDT01QQVRJQkxFX01PREUiO3M6MToiTiI7czoxNToiQkFTS0VUX1BPU0lUSU9OIjtzOjY6ImJlZm9yZSI7czoyMToiQkFTS0VUX0lNQUdFU19TQ0FMSU5HIjtzOjg6ImFkYXB0aXZlIjtzOjIzOiJTRVJWSUNFU19JTUFHRVNfU0NBTElORyI7czo4OiJhZGFwdGl2ZSI7czoxMjoiVVNFUl9DT05TRU5UIjtzOjE6IlkiO3M6MTU6IlVTRVJfQ09OU0VOVF9JRCI7czoxOiIyIjtzOjIzOiJVU0VSX0NPTlNFTlRfSVNfQ0hFQ0tFRCI7czoxOiJZIjtzOjIyOiJVU0VSX0NPTlNFTlRfSVNfTE9BREVEIjtzOjE6IlkiO3M6MTA6IkNBQ0hFX1RZUEUiO3M6MToiQSI7czoxMToiVVNFX1BSRUxPQUQiO3M6MToiWSI7czoxNToiQUNUSU9OX1ZBUklBQkxFIjtzOjEwOiJzb2EtYWN0aW9uIjtzOjExOiJOT19QRVJTT05BTCI7czoxOiJOIjtzOjEyOiJQQVRIX1RPX0FVVEgiO3M6NjoiL2F1dGgvIjtzOjE0OiJVU0VfUFJFUEFZTUVOVCI7czoxOiJOIjtzOjE4OiJESVNQTEFZX0lNR19IRUlHSFQiO2k6OTA7czoxNDoiU0hPV19WQVRfUFJJQ0UiO3M6MToiWSI7czoyMToiREVMSVZFUllfVE9fUEFZU1lTVEVNIjtzOjM6ImQycCI7czoyMzoiRElTQUJMRV9CQVNLRVRfUkVESVJFQ1QiO3M6MToiTiI7czoyMjoiRU1QVFlfQkFTS0VUX0hJTlRfUEFUSCI7czoxOiIvIjtzOjEyOiJDVVJSRU5UX1BBR0UiO3M6MzE6Ii9wZXJzb25hbC9vcmRlci9tYWtlL2luZGV4NC5waHAiO3M6MTU6IklTX0xBTkRJTkdfU0hPUCI7czoxOiJOIjtzOjE4OiJBTExPV19BUFBFTkRfT1JERVIiO3M6MToiWSI7czoxNzoiQUxMT1dfTkVXX1BST0ZJTEUiO3M6MToiWSI7czozMDoiU0hPV19OT1RfQ0FMQ1VMQVRFRF9ERUxJVkVSSUVTIjtzOjE6IlkiO3M6MjI6IlNQT1RfTE9DQVRJT05fQllfR0VPSVAiO3M6MToiWSI7czoxNToiUFJPRFVDVF9DT0xVTU5TIjthOjU6e3M6NDoiTkFNRSI7czoxNjoi0J3QsNC30LLQsNC90LjQtSI7czoxNToiUFJFVklFV19QSUNUVVJFIjtzOjIyOiLQmNC30L7QsdGA0LDQttC10L3QuNC1IjtzOjU6IlBST1BTIjtzOjE2OiLQodCy0L7QudGB0YLQstCwIjtzOjg6IlFVQU5USVRZIjtzOjIwOiLQmtC+0LvQuNGH0LXRgdGC0LLQviI7czozOiJTVU0iO3M6MTA6ItCh0YPQvNC80LAiO31zOjIzOiJQUk9EVUNUX0NPTFVNTlNfVklTSUJMRSI7YToyOntpOjA7czoxNToiUFJFVklFV19QSUNUVVJFIjtpOjE7czo1OiJQUk9QUyI7fXM6MjI6IlBST0RVQ1RfQ09MVU1OU19ISURERU4iO2E6MDp7fXM6MjM6IlVTRV9QSE9ORV9OT1JNQUxJWkFUSU9OIjtzOjE6IlkiO3M6MTc6In5QQVlfRlJPTV9BQ0NPVU5UIjtzOjE6IlkiO3M6MTk6In5DT1VOVF9ERUxJVkVSWV9UQVgiO3M6MToiTiI7czozMDoifkNPVU5UX0RJU0NPVU5UXzRfQUxMX1FVQU5USVRZIjtzOjE6Ik4iO3M6Mjc6In5PTkxZX0ZVTExfUEFZX0ZST01fQUNDT1VOVCI7czoxOiJOIjtzOjIwOiJ+QUxMT1dfQVVUT19SRUdJU1RFUiI7czoxOiJZIjtzOjIxOiJ+U0VORF9ORVdfVVNFUl9OT1RJRlkiO3M6MToiWSI7czoxNzoifkRFTElWRVJZX05PX0FKQVgiO3M6MToiTiI7czoxODoiflRFTVBMQVRFX0xPQ0FUSU9OIjtzOjU6InBvcHVwIjtzOjc6In5QUk9QXzEiO2E6MDp7fXM6MTU6In5QQVRIX1RPX0JBU0tFVCI7czoxNToiL3BlcnNvbmFsL2NhcnQvIjtzOjE3OiJ+UEFUSF9UT19QRVJTT05BTCI7czoxNjoiL3BlcnNvbmFsL29yZGVyLyI7czoxNjoiflBBVEhfVE9fUEFZTUVOVCI7czoyNDoiL3BlcnNvbmFsL29yZGVyL3BheW1lbnQvIjtzOjE0OiJ+UEFUSF9UT19PUkRFUiI7czoyMToiL3BlcnNvbmFsL29yZGVyL21ha2UvIjtzOjEwOiJ+U0VUX1RJVExFIjtzOjE6IlkiO3M6MjA6In5TSE9XX0FDQ09VTlRfTlVNQkVSIjtzOjE6IlkiO3M6MjA6In5ERUxJVkVSWV9OT19TRVNTSU9OIjtzOjE6IlkiO3M6MTY6In5DT01QQVRJQkxFX01PREUiO3M6MToiTiI7czoxNjoifkJBU0tFVF9QT1NJVElPTiI7czo2OiJiZWZvcmUiO3M6MjI6In5CQVNLRVRfSU1BR0VTX1NDQUxJTkciO3M6ODoiYWRhcHRpdmUiO3M6MjQ6In5TRVJWSUNFU19JTUFHRVNfU0NBTElORyI7czo4OiJhZGFwdGl2ZSI7czoxMzoiflVTRVJfQ09OU0VOVCI7czoxOiJZIjtzOjE2OiJ+VVNFUl9DT05TRU5UX0lEIjtzOjE6IjIiO3M6MjQ6In5VU0VSX0NPTlNFTlRfSVNfQ0hFQ0tFRCI7czoxOiJZIjtzOjIzOiJ+VVNFUl9DT05TRU5UX0lTX0xPQURFRCI7czoxOiJZIjtzOjExOiJ+Q0FDSEVfVFlQRSI7czoxOiJBIjtzOjEyOiJ+VVNFX1BSRUxPQUQiO3M6MToiWSI7czoxNjoifkFDVElPTl9WQVJJQUJMRSI7czoxMDoic29hLWFjdGlvbiI7czoxMjoifk5PX1BFUlNPTkFMIjtzOjE6Ik4iO3M6MTM6In5QQVRIX1RPX0FVVEgiO3M6NjoiL2F1dGgvIjtzOjE1OiJ+VVNFX1BSRVBBWU1FTlQiO3M6MToiTiI7czoxOToifkRJU1BMQVlfSU1HX0hFSUdIVCI7aTo5MDtzOjE1OiJ+U0hPV19WQVRfUFJJQ0UiO3M6MToiWSI7czoyMjoifkRFTElWRVJZX1RPX1BBWVNZU1RFTSI7czozOiJkMnAiO3M6MjQ6In5ESVNBQkxFX0JBU0tFVF9SRURJUkVDVCI7czoxOiJOIjtzOjIzOiJ+RU1QVFlfQkFTS0VUX0hJTlRfUEFUSCI7czoxOiIvIjtzOjEzOiJ+Q1VSUkVOVF9QQUdFIjtzOjMxOiIvcGVyc29uYWwvb3JkZXIvbWFrZS9pbmRleDQucGhwIjtzOjE2OiJ+SVNfTEFORElOR19TSE9QIjtzOjE6Ik4iO3M6MTk6In5BTExPV19BUFBFTkRfT1JERVIiO3M6MToiWSI7czoxODoifkFMTE9XX05FV19QUk9GSUxFIjtzOjE6IlkiO3M6MzE6In5TSE9XX05PVF9DQUxDVUxBVEVEX0RFTElWRVJJRVMiO3M6MToiWSI7czoyMzoiflNQT1RfTE9DQVRJT05fQllfR0VPSVAiO3M6MToiWSI7czoxNjoiflBST0RVQ1RfQ09MVU1OUyI7YTo1OntzOjQ6Ik5BTUUiO3M6MTY6ItCd0LDQt9Cy0LDQvdC40LUiO3M6MTU6IlBSRVZJRVdfUElDVFVSRSI7czoyMjoi0JjQt9C+0LHRgNCw0LbQtdC90LjQtSI7czo1OiJQUk9QUyI7czoxNjoi0KHQstC+0LnRgdGC0LLQsCI7czo4OiJRVUFOVElUWSI7czoyMDoi0JrQvtC70LjRh9C10YHRgtCy0L4iO3M6MzoiU1VNIjtzOjEwOiLQodGD0LzQvNCwIjt9czoyNDoiflBST0RVQ1RfQ09MVU1OU19WSVNJQkxFIjthOjI6e2k6MDtzOjE1OiJQUkVWSUVXX1BJQ1RVUkUiO2k6MTtzOjU6IlBST1BTIjt9czoyMzoiflBST0RVQ1RfQ09MVU1OU19ISURERU4iO2E6MDp7fXM6MjQ6In5VU0VfUEhPTkVfTk9STUFMSVpBVElPTiI7czoxOiJZIjtzOjE0OiJURU1QTEFURV9USEVNRSI7czowOiIiO3M6MTc6IlNIT1dfT1JERVJfQlVUVE9OIjtzOjEwOiJmaW5hbF9zdGVwIjtzOjIzOiJTSE9XX1RPVEFMX09SREVSX0JVVFRPTiI7czoxOiJOIjtzOjI2OiJTSE9XX1BBWV9TWVNURU1fTElTVF9OQU1FUyI7czoxOiJZIjtzOjI1OiJTSE9XX1BBWV9TWVNURU1fSU5GT19OQU1FIjtzOjE6IlkiO3M6MjQ6IlNIT1dfREVMSVZFUllfTElTVF9OQU1FUyI7czoxOiJZIjtzOjIzOiJTSE9XX0RFTElWRVJZX0lORk9fTkFNRSI7czoxOiJZIjtzOjI2OiJTSE9XX0RFTElWRVJZX1BBUkVOVF9OQU1FUyI7czoxOiJZIjtzOjE4OiJTSE9XX1NUT1JFU19JTUFHRVMiO3M6MToiWSI7czoxODoiU0tJUF9VU0VMRVNTX0JMT0NLIjtzOjE6IlkiO3M6MTk6IlNIT1dfQkFTS0VUX0hFQURFUlMiO3M6MToiTiI7czoyODoiREVMSVZFUllfRkFERV9FWFRSQV9TRVJWSUNFUyI7czoxOiJOIjtzOjE5OiJTSE9XX05FQVJFU1RfUElDS1VQIjtzOjE6Ik4iO3M6MTk6IkRFTElWRVJJRVNfUEVSX1BBR0UiO2k6OTtzOjIwOiJQQVlfU1lTVEVNU19QRVJfUEFHRSI7aTo5O3M6MTY6IlBJQ0tVUFNfUEVSX1BBR0UiO2k6NTtzOjE1OiJTSE9XX1BJQ0tVUF9NQVAiO3M6MToiWSI7czoxNzoiU0hPV19NQVBfSU5fUFJPUFMiO3M6MToiTiI7czoxNToiUElDS1VQX01BUF9UWVBFIjtzOjY6InlhbmRleCI7czoyMjoiSElERV9PUkRFUl9ERVNDUklQVElPTiI7czoxOiJOIjtzOjE5OiJBTExPV19VU0VSX1BST0ZJTEVTIjtzOjE6Ik4iO3M6MTI6IlNIT1dfQ09VUE9OUyI7czoxOiJZIjtzOjE5OiJTSE9XX0NPVVBPTlNfQkFTS0VUIjtzOjE6IlkiO3M6MjE6IlNIT1dfQ09VUE9OU19ERUxJVkVSWSI7czoxOiJZIjtzOjIzOiJTSE9XX0NPVVBPTlNfUEFZX1NZU1RFTSI7czoxOiJZIjtzOjEyOiJVU0VfWU1fR09BTFMiO3M6MToiTiI7czoxNjoiWU1fR09BTFNfQ09VTlRFUiI7czowOiIiO3M6MTk6IllNX0dPQUxTX0lOSVRJQUxJWkUiO3M6MTM6IkJYLW9yZGVyLWluaXQiO3M6MjA6IllNX0dPQUxTX0VESVRfUkVHSU9OIjtzOjE0OiJCWC1yZWdpb24tZWRpdCI7czoyMjoiWU1fR09BTFNfRURJVF9ERUxJVkVSWSI7czoxNjoiQlgtZGVsaXZlcnktZWRpdCI7czoyMDoiWU1fR09BTFNfRURJVF9QSUNLVVAiO3M6MTQ6IkJYLXBpY2tVcC1lZGl0IjtzOjI0OiJZTV9HT0FMU19FRElUX1BBWV9TWVNURU0iO3M6MTc6IkJYLXBheVN5c3RlbS1lZGl0IjtzOjI0OiJZTV9HT0FMU19FRElUX1BST1BFUlRJRVMiO3M6MTg6IkJYLXByb3BlcnRpZXMtZWRpdCI7czoyMDoiWU1fR09BTFNfRURJVF9CQVNLRVQiO3M6MTQ6IkJYLWJhc2tldC1lZGl0IjtzOjIwOiJZTV9HT0FMU19ORVhUX1JFR0lPTiI7czoxNDoiQlgtcmVnaW9uLW5leHQiO3M6MjI6IllNX0dPQUxTX05FWFRfREVMSVZFUlkiO3M6MTY6IkJYLWRlbGl2ZXJ5LW5leHQiO3M6MjA6IllNX0dPQUxTX05FWFRfUElDS1VQIjtzOjE0OiJCWC1waWNrVXAtbmV4dCI7czoyNDoiWU1fR09BTFNfTkVYVF9QQVlfU1lTVEVNIjtzOjE3OiJCWC1wYXlTeXN0ZW0tbmV4dCI7czoyNDoiWU1fR09BTFNfTkVYVF9QUk9QRVJUSUVTIjtzOjE4OiJCWC1wcm9wZXJ0aWVzLW5leHQiO3M6MjA6IllNX0dPQUxTX05FWFRfQkFTS0VUIjtzOjE0OiJCWC1iYXNrZXQtbmV4dCI7czoxOToiWU1fR09BTFNfU0FWRV9PUkRFUiI7czoxMzoiQlgtb3JkZXItc2F2ZSI7czoyMjoiVVNFX0VOSEFOQ0VEX0VDT01NRVJDRSI7czoxOiJOIjtzOjE1OiJEQVRBX0xBWUVSX05BTUUiO3M6OToiZGF0YUxheWVyIjtzOjE0OiJCUkFORF9QUk9QRVJUWSI7czowOiIiO3M6MjM6IlNIT1dfTUFQX0ZPUl9ERUxJVkVSSUVTIjthOjA6e31zOjIwOiJISURFX0RFVEFJTF9QQUdFX1VSTCI7czoxOiJOIjtzOjIwOiJNRVNTX0FVVEhfQkxPQ0tfTkFNRSI7czoyMjoi0JDQstGC0L7RgNC40LfQsNGG0LjRjyI7czoxOToiTUVTU19SRUdfQkxPQ0tfTkFNRSI7czoyMjoi0KDQtdCz0LjRgdGC0YDQsNGG0LjRjyI7czoyMjoiTUVTU19CQVNLRVRfQkxPQ0tfTkFNRSI7czoyODoi0KLQvtCy0LDRgNGLINCyINC30LDQutCw0LfQtSI7czoyMjoiTUVTU19SRUdJT05fQkxPQ0tfTkFNRSI7czoyOToi0KDQtdCz0LjQvtC9INC00L7RgdGC0LDQstC60LgiO3M6MjM6Ik1FU1NfUEFZTUVOVF9CTE9DS19OQU1FIjtzOjEyOiLQntC/0LvQsNGC0LAiO3M6MjQ6Ik1FU1NfREVMSVZFUllfQkxPQ0tfTkFNRSI7czoxNjoi0JTQvtGB0YLQsNCy0LrQsCI7czoyMToiTUVTU19CVVlFUl9CTE9DS19OQU1FIjtzOjIwOiLQn9C+0LrRg9C/0LDRgtC10LvRjCI7czo5OiJNRVNTX0JBQ0siO3M6MTA6ItCd0LDQt9Cw0LQiO3M6MTI6Ik1FU1NfRlVSVEhFUiI7czoxMDoi0JTQsNC70LXQtSI7czo5OiJNRVNTX0VESVQiO3M6MTY6ItC40LfQvNC10L3QuNGC0YwiO3M6MTE6In5NRVNTX09SREVSIjtzOjI3OiLQntGE0L7RgNC80LjRgtGMINC30LDQutCw0LciO3M6MTA6Ik1FU1NfT1JERVIiO3M6Mjc6ItCe0YTQvtGA0LzQuNGC0Ywg0LfQsNC60LDQtyI7czoxMDoiTUVTU19QUklDRSI7czoxODoi0KHRgtC+0LjQvNC+0YHRgtGMIjtzOjExOiJNRVNTX1BFUklPRCI7czoyNToi0KHRgNC+0Log0LTQvtGB0YLQsNCy0LrQuCI7czoxMzoiTUVTU19OQVZfQkFDSyI7czoxMDoi0J3QsNC30LDQtCI7czoxNjoiTUVTU19OQVZfRk9SV0FSRCI7czoxMjoi0JLQv9C10YDQtdC0IjtzOjE1OiJNRVNTX1BSSUNFX0ZSRUUiO3M6MTg6ItCx0LXRgdC/0LvQsNGC0L3QviI7czoxMjoiTUVTU19FQ09OT01ZIjtzOjE2OiLQrdC60L7QvdC+0LzQuNGPIjtzOjI3OiJNRVNTX1JFR0lTVFJBVElPTl9SRUZFUkVOQ0UiO3M6MjE5OiLQldGB0LvQuCDQstGLINCy0L/QtdGA0LLRi9C1INC90LAg0YHQsNC50YLQtSwg0Lgg0YXQvtGC0LjRgtC1LCDRh9GC0L7QsdGLINC80Ysg0LLQsNGBINC/0L7QvNC90LjQu9C4LCDQuCDQstGB0LUg0LLQsNGI0Lgg0LfQsNC60LDQt9GLINGB0L7RhdGA0LDQvdGP0LvQuNGB0YwsINC30LDQv9C+0LvQvdC40YLQtSDRgNC10LPQuNGB0YLRgNCw0YbQuNC+0L3QvdGD0Y4g0YTQvtGA0LzRgy4iO3M6MjE6Ik1FU1NfQVVUSF9SRUZFUkVOQ0VfMSI7czoxMjE6ItCh0LjQvNCy0L7Qu9C+0LwgItC30LLQtdC30LTQvtGH0LrQsCIgKCopINC+0YLQvNC10YfQtdC90Ysg0L7QsdGP0LfQsNGC0LXQu9GM0L3Ri9C1INC00LvRjyDQt9Cw0L/QvtC70L3QtdC90LjRjyDQv9C+0LvRjy4iO3M6MjE6Ik1FU1NfQVVUSF9SRUZFUkVOQ0VfMiI7czo5ODoi0J/QvtGB0LvQtSDRgNC10LPQuNGB0YLRgNCw0YbQuNC4INCy0Ysg0L/QvtC70YPRh9C40YLQtSDQuNC90YTQvtGA0LzQsNGG0LjQvtC90L3QvtC1INC/0LjRgdGM0LzQvi4iO3M6MjE6Ik1FU1NfQVVUSF9SRUZFUkVOQ0VfMyI7czo0Nzk6ItCb0LjRh9C90YvQtSDRgdCy0LXQtNC10L3QuNGPLCDQv9C+0LvRg9GH0LXQvdC90YvQtSDQsiDRgNCw0YHQv9C+0YDRj9C20LXQvdC40LUg0LjQvdGC0LXRgNC90LXRgi3QvNCw0LPQsNC30LjQvdCwINC/0YDQuCDRgNC10LPQuNGB0YLRgNCw0YbQuNC4INC40LvQuCDQutCw0LrQuNC8LdC70LjQsdC+INC40L3Ri9C8INC+0LHRgNCw0LfQvtC8LCDQvdC1INCx0YPQtNGD0YIg0LHQtdC3INGA0LDQt9GA0LXRiNC10L3QuNGPINC/0L7Qu9GM0LfQvtCy0LDRgtC10LvQtdC5INC/0LXRgNC10LTQsNCy0LDRgtGM0YHRjyDRgtGA0LXRgtGM0LjQvCDQvtGA0LPQsNC90LjQt9Cw0YbQuNGP0Lwg0Lgg0LvQuNGG0LDQvCDQt9CwINC40YHQutC70Y7Rh9C10L3QuNC10Lwg0YHQuNGC0YPQsNGG0LjQuSwg0LrQvtCz0LTQsCDRjdGC0L7Qs9C+INGC0YDQtdCx0YPQtdGCINC30LDQutC+0L0g0LjQu9C4INGB0YPQtNC10LHQvdC+0LUg0YDQtdGI0LXQvdC40LUuIjtzOjIxOiJNRVNTX0FERElUSU9OQUxfUFJPUFMiO3M6NDU6ItCU0L7Qv9C+0LvQvdC40YLQtdC70YzQvdGL0LUg0YHQstC+0LnRgdGC0LLQsCI7czoxNToiTUVTU19VU0VfQ09VUE9OIjtzOjI5OiLQn9GA0LjQvNC10L3QuNGC0Ywg0LrRg9C/0L7QvSI7czoxMToiTUVTU19DT1VQT04iO3M6MTA6ItCa0YPQv9C+0L0iO3M6MTY6Ik1FU1NfUEVSU09OX1RZUEUiO3M6Mjk6ItCi0LjQvyDQv9C70LDRgtC10LvRjNGJ0LjQutCwIjtzOjE5OiJNRVNTX1NFTEVDVF9QUk9GSUxFIjtzOjMxOiLQktGL0LHQtdGA0LjRgtC1INC/0YDQvtGE0LjQu9GMIjtzOjIxOiJNRVNTX1JFR0lPTl9SRUZFUkVOQ0UiO3M6MjIwOiLQktGL0LHQtdGA0LjRgtC1INGB0LLQvtC5INCz0L7RgNC+0LQg0LIg0YHQv9C40YHQutC1LiDQldGB0LvQuCDQstGLINC90LUg0L3QsNGI0LvQuCDRgdCy0L7QuSDQs9C+0YDQvtC0LCDQstGL0LHQtdGA0LjRgtC1ICLQtNGA0YPQs9C+0LUg0LzQtdGB0YLQvtC/0L7Qu9C+0LbQtdC90LjQtSIsINCwINCz0L7RgNC+0LQg0LLQv9C40YjQuNGC0LUg0LIg0L/QvtC70LUgItCT0L7RgNC+0LQiIjtzOjE2OiJNRVNTX1BJQ0tVUF9MSVNUIjtzOjM0OiLQn9GD0L3QutGC0Ysg0YHQsNC80L7QstGL0LLQvtC30LA6IjtzOjI0OiJNRVNTX05FQVJFU1RfUElDS1VQX0xJU1QiO3M6MzI6ItCR0LvQuNC20LDQudGI0LjQtSDQv9GD0L3QutGC0Ys6IjtzOjE4OiJNRVNTX1NFTEVDVF9QSUNLVVAiO3M6MTQ6ItCS0YvQsdGA0LDRgtGMIjtzOjIxOiJNRVNTX0lOTkVSX1BTX0JBTEFOQ0UiO3M6NjA6ItCd0LAg0LLQsNGI0LXQvCDQv9C+0LvRjNC30L7QstCw0YLQtdC70YzRgdC60L7QvCDRgdGH0LXRgtC1OiI7czoxNToiTUVTU19PUkRFUl9ERVNDIjtzOjM5OiLQmtC+0LzQvNC10L3RgtCw0YDQuNC4INC6INC30LDQutCw0LfRgzoiO3M6MjQ6Ik1FU1NfUFJFTE9BRF9PUkRFUl9USVRMRSI7TjtzOjI1OiJNRVNTX1NVQ0NFU1NfUFJFTE9BRF9URVhUIjtzOjI2MToi0JLRiyDQt9Cw0LrQsNC30YvQstCw0LvQuCDQsiDQvdCw0YjQtdC8INC40L3RgtC10YDQvdC10YIt0LzQsNCz0LDQt9C40L3QtSwg0L/QvtGN0YLQvtC80YMg0LzRiyDQt9Cw0L/QvtC70L3QuNC70Lgg0LLRgdC1INC00LDQvdC90YvQtSDQsNCy0YLQvtC80LDRgtC40YfQtdGB0LrQuC48YnIgLz4K0JXRgdC70Lgg0LLRgdC1INC30LDQv9C+0LvQvdC10L3QviDQstC10YDQvdC+LCDQvdCw0LbQvNC40YLQtSDQutC90L7Qv9C60YMgIiNPUkRFUl9CVVRUT04jIi4KIjtzOjIyOiJNRVNTX0ZBSUxfUFJFTE9BRF9URVhUIjtzOjQ1NDoi0JLRiyDQt9Cw0LrQsNC30YvQstCw0LvQuCDQsiDQvdCw0YjQtdC8INC40L3RgtC10YDQvdC10YIt0LzQsNCz0LDQt9C40L3QtSwg0L/QvtGN0YLQvtC80YMg0LzRiyDQt9Cw0L/QvtC70L3QuNC70Lgg0LLRgdC1INC00LDQvdC90YvQtSDQsNCy0YLQvtC80LDRgtC40YfQtdGB0LrQuC48YnIgLz4K0J7QsdGA0LDRgtC40YLQtSDQstC90LjQvNCw0L3QuNC1INC90LAg0YDQsNC30LLQtdGA0L3Rg9GC0YvQuSDQsdC70L7QuiDRgSDQuNC90YTQvtGA0LzQsNGG0LjQtdC5INC+INC30LDQutCw0LfQtS4g0JfQtNC10YHRjCDQstGLINC80L7QttC10YLQtSDQstC90LXRgdGC0Lgg0L3QtdC+0LHRhdC+0LTQuNC80YvQtSDQuNC30LzQtdC90LXQvdC40Y8g0LjQu9C4IArQvtGB0YLQsNCy0LjRgtGMINC60LDQuiDQtdGB0YLRjCDQuCDQvdCw0LbQsNGC0Ywg0LrQvdC+0L/QutGDICIjT1JERVJfQlVUVE9OIyIuCiI7czozMDoiTUVTU19ERUxJVkVSWV9DQUxDX0VSUk9SX1RJVExFIjtzOjc3OiLQndC1INGD0LTQsNC70L7RgdGMINGA0LDRgdGB0YfQuNGC0LDRgtGMINGB0YLQvtC40LzQvtGB0YLRjCDQtNC+0YHRgtCw0LLQutC4LiI7czoyOToiTUVTU19ERUxJVkVSWV9DQUxDX0VSUk9SX1RFWFQiO3M6MjIxOiLQktGLINC80L7QttC10YLQtSDQv9GA0L7QtNC+0LvQttC40YLRjCDQvtGE0L7RgNC80LvQtdC90LjQtSDQt9Cw0LrQsNC30LAsINCwINGH0YPRgtGMINC/0L7Qt9C20LUg0LzQtdC90LXQtNC20LXRgCDQvNCw0LPQsNC30LjQvdCwINGB0LLRj9C20LXRgtGB0Y8g0YEg0LLQsNC80Lgg0Lgg0YPRgtC+0YfQvdC40YIg0LjQvdGE0L7RgNC80LDRhtC40Y4g0L/QviDQtNC+0YHRgtCw0LLQutC1LiI7czoyOToiTUVTU19QQVlfU1lTVEVNX1BBWUFCTEVfRVJST1IiO3M6NDE4OiLQktGLINGB0LzQvtC20LXRgtC1INC+0L/Qu9Cw0YLQuNGC0Ywg0LfQsNC60LDQtyDQv9C+0YHQu9C1INGC0L7Qs9C+LCDQutCw0Log0LzQtdC90LXQtNC20LXRgCDQv9GA0L7QstC10YDQuNGCINC90LDQu9C40YfQuNC1INC/0L7Qu9C90L7Qs9C+INC60L7QvNC/0LvQtdC60YLQsCDRgtC+0LLQsNGA0L7QsiDQvdCwINGB0LrQu9Cw0LTQtS4g0KHRgNCw0LfRgyDQv9C+0YHQu9C1INC/0YDQvtCy0LXRgNC60Lgg0LLRiyDQv9C+0LvRg9GH0LjRgtC1INC/0LjRgdGM0LzQviDRgSDQuNC90YHRgtGA0YPQutGG0LjRj9C80Lgg0L/QviDQvtC/0LvQsNGC0LUuINCe0L/Qu9Cw0YLQuNGC0Ywg0LfQsNC60LDQtyDQvNC+0LbQvdC+INCx0YPQtNC10YIg0LIg0L/QtdGA0YHQvtC90LDQu9GM0L3QvtC8INGA0LDQt9C00LXQu9C1INGB0LDQudGC0LAuIjt9.df6f424f0972b4ef482c2819c94659d9bad9ada6e16e748b512622e30fc22cbe',
			siteID: 's1',
			ajaxUrl: '/bitrix/components/bitrix/sale.order.ajax/ajax.php',
			templateFolder: '/bitrix/components/bitrix/sale.order.ajax/templates/bootstrap_v4',
			propertyValidation: true,
			showWarnings: true,
			pickUpMap: {
				defaultMapPosition: {
					lat: 55.76,
					lon: 37.64,
					zoom: 7
				},
				secureGeoLocation: false,
				geoLocationMaxTime: 5000,
				minToShowNearestBlock: 3,
				nearestPickUpsToShow: 3
			},
			propertyMap: {
				defaultMapPosition: {
					lat: 55.76,
					lon: 37.64,
					zoom: 7
				}
			},
		},
	});
	
	twpxordermake.run();
</script>
